services:
  mariadb-bill:
    image: mariadb:latest
    container_name: mariadb-bill
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bill-db
      MYSQL_USER: user
      MYSQL_PASSWORD: factpass
    ports:
    - "3307:3306"
  rabbitmq:
        image: rabbitmq:3-management 
        container_name: rabbitmq-videos
        ports:
        - "5672:5672"       
        - "15672:15672"    
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest