services:
  mariadb-bill:
    image: mariadb:latest
    container_name: mariadb-bill
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bill-db
      MYSQL_USER: user
      MYSQL_PASSWORD: factpass
    ports:
    - "3307:3306"
